### ISSUE TITLE
todo: Google sheet -> Pandas DataFrame

### ISSUE THREAD

**Issue by jacobdadams** [agrc/pj-uorg#1]
Load a google sheet into a pandas dataframe for easy updating
Use pygsheets: https://pygsheets.readthedocs.io/en/stable/

- [ ] need to figure out GCP auth

**Comment by steveoh** [comment]
A few of us in the office have experience with auth and sheets. Feel free to talk to rick, zach, scott, or me about it.

**Comment by jacobdadams** [comment]
closed by agrc/palletjack#7
